"""add_user_roles_json_field

Revision ID: 0444a3097a83
Revises: 9c67ed1c6579
Create Date: 2025-09-06 15:51:54.695693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0444a3097a83'
down_revision: Union[str, Sequence[str], None] = '9c67ed1c6579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем новую колонку roles
    op.add_column('users', sa.Column('roles', sa.JSON(), nullable=False, server_default='["applicant"]'))
    
    # Обновляем существующих пользователей - копируем роль в массив ролей
    op.execute("""
        UPDATE users 
        SET roles = CASE 
            WHEN role = 'owner' THEN '["owner"]'::json
            WHEN role = 'employee' THEN '["employee"]'::json
            WHEN role = 'superadmin' THEN '["superadmin"]'::json
            ELSE '["applicant"]'::json
        END
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем колонку roles
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###
