"""add_schedule_link_to_shifts

Revision ID: 187db2e835ad
Revises: 92638490b2e0
Create Date: 2025-09-07 16:11:50.161321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '187db2e835ad'
down_revision: Union[str, Sequence[str], None] = '92638490b2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('schedule_id', sa.Integer(), nullable=True))
    op.add_column('shifts', sa.Column('is_planned', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_shifts_schedule_id'), 'shifts', ['schedule_id'], unique=False)
    op.create_foreign_key('fk_shifts_schedule_id', 'shifts', 'shift_schedules', ['schedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_shifts_schedule_id', 'shifts', type_='foreignkey')
    op.drop_index(op.f('ix_shifts_schedule_id'), 'shifts')
    op.drop_column('shifts', 'is_planned')
    op.drop_column('shifts', 'schedule_id')
    # ### end Alembic commands ###