"""add_work_schedule_fields_to_objects

Revision ID: 339dc32e8c69
Revises: a5f7d64c9e0b
Create Date: 2025-09-10 14:02:33.932659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '339dc32e8c69'
down_revision: Union[str, Sequence[str], None] = 'a5f7d64c9e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('work_days_mask', sa.Integer(), server_default='31', nullable=False))
    op.add_column('objects', sa.Column('schedule_repeat_weeks', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'schedule_repeat_weeks')
    op.drop_column('objects', 'work_days_mask')
    # ### end Alembic commands ###
