"""add_available_for_applicants_to_objects

Revision ID: 4b2fa139dbe2
Revises: 0444a3097a83
Create Date: 2025-09-06 17:57:25.366652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2fa139dbe2'
down_revision: Union[str, Sequence[str], None] = '0444a3097a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('available_for_applicants', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'available_for_applicants')
    # ### end Alembic commands ###
