"""add employee_position field to objects table

Revision ID: 6ddec8a028d4
Revises: be8f7da4f7ec
Create Date: 2025-09-25 15:53:44.414542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ddec8a028d4'
down_revision: Union[str, Sequence[str], None] = 'be8f7da4f7ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('employee_position', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'employee_position')
    # ### end Alembic commands ###
