"""make_object_id_nullable_in_planning_templates

Revision ID: 7d2f3a2b54d1
Revises: cdf426d5d4ec
Create Date: 2025-09-07 07:49:23.044429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d2f3a2b54d1'
down_revision: Union[str, Sequence[str], None] = 'cdf426d5d4ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planning_templates', 'object_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='ID объекта (null для универсальных шаблонов)',
               existing_comment='ID объекта')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planning_templates', 'object_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='ID объекта',
               existing_comment='ID объекта (null для универсальных шаблонов)')
    # ### end Alembic commands ###
