"""добавлены_поля_профиля_пользователя

Revision ID: 8f5fd7e8c46c
Revises: 0d33e3b1ae29
Create Date: 2025-09-23 19:58:22.064134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f5fd7e8c46c'
down_revision: Union[str, Sequence[str], None] = '0d33e3b1ae29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('work_experience', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('education', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('skills', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('about', sa.String(length=2000), nullable=True))
    op.add_column('users', sa.Column('preferred_schedule', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('min_salary', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('availability_notes', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'availability_notes')
    op.drop_column('users', 'min_salary')
    op.drop_column('users', 'preferred_schedule')
    op.drop_column('users', 'about')
    op.drop_column('users', 'skills')
    op.drop_column('users', 'education')
    op.drop_column('users', 'work_experience')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
