"""add_time_slot_id_to_shifts

Revision ID: 90f267d839c9
Revises: 0157a54a5e7e
Create Date: 2025-09-06 09:21:55.155902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f267d839c9'
down_revision: Union[str, Sequence[str], None] = '0157a54a5e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = '20250828_add_time_slots_table'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shift_schedules', 'auto_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('shifts', sa.Column('time_slot_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_shifts_time_slot_id'), 'shifts', ['time_slot_id'], unique=False)
    op.create_foreign_key(None, 'shifts', 'time_slots', ['time_slot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shifts', type_='foreignkey')
    op.drop_index(op.f('ix_shifts_time_slot_id'), table_name='shifts')
    op.drop_column('shifts', 'time_slot_id')
    op.alter_column('shift_schedules', 'auto_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
