"""Add max_distance_meters to objects table

Revision ID: 97844e8c2d47
Revises: 4b2855b94366
Create Date: 2025-08-21 10:46:16.065160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97844e8c2d47'
down_revision: Union[str, Sequence[str], None] = '4b2855b94366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('objects', sa.Column('max_distance_meters', sa.Integer(), nullable=False, server_default='500'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'max_distance_meters')
    # ### end Alembic commands ###
