"""Добавлено поле timezone к объектам

Revision ID: 9e47662cd158
Revises: 339dc32e8c69
Create Date: 2025-09-14 11:41:14.245020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e47662cd158'
down_revision: Union[str, Sequence[str], None] = '339dc32e8c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем поле timezone к объектам
    op.add_column('objects', sa.Column('timezone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('objects', 'timezone')
    # ### end Alembic commands ###