"""add_organization_profiles_and_system_features

Revision ID: a266c36de460
Revises: aa667829206d
Create Date: 2025-10-19 11:51:21.652268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a266c36de460'
down_revision: Union[str, Sequence[str], None] = 'aa667829206d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False, comment='Уникальный ключ функции (например: shared_calendar)'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='Человекочитаемое название функции'),
    sa.Column('description', sa.Text(), nullable=True, comment='Продающее описание функции'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='Порядок сортировки в интерфейсе'),
    sa.Column('menu_items', sa.JSON(), nullable=False, comment='Список ID пунктов меню, связанных с функцией'),
    sa.Column('form_elements', sa.JSON(), nullable=False, comment='Список ID элементов форм, связанных с функцией'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Активна ли функция в системе (глобально)'),
    sa.Column('usage_count', sa.Integer(), nullable=False, comment='Счетчик использования функции'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_features_id'), 'system_features', ['id'], unique=False)
    op.create_index(op.f('ix_system_features_key'), 'system_features', ['key'], unique=True)
    op.create_table('organization_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя-владельца'),
    sa.Column('profile_name', sa.String(length=200), nullable=False, comment='Название профиля (например: ИП Иванов, ООО Ромашка)'),
    sa.Column('legal_type', sa.String(length=20), nullable=False, comment='Тип: individual (ФЛ/ИП) или legal (ЮЛ)'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='Профиль по умолчанию для данного пользователя'),
    sa.Column('requisites', sa.JSON(), nullable=False, comment='Реквизиты ИП или ЮЛ в формате {field_name: value}'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_profiles_id'), 'organization_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_organization_profiles_user_id'), 'organization_profiles', ['user_id'], unique=False)
    # Не удаляем spatial_ref_sys - системная таблица PostGIS
    # op.drop_table('spatial_ref_sys')
    op.drop_index('ix_system_settings_id', table_name='system_settings')
    op.drop_index('ix_system_settings_key', table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index('idx_shift_tasks_id', table_name='shift_tasks')
    op.drop_index('idx_shift_tasks_is_completed', table_name='shift_tasks')
    op.drop_index('idx_shift_tasks_is_mandatory', table_name='shift_tasks')
    op.drop_index('idx_shift_tasks_shift_id', table_name='shift_tasks')
    op.drop_index('idx_shift_tasks_source', table_name='shift_tasks')
    op.drop_table('shift_tasks')
    # КРИТИЧНО: НЕ УДАЛЯЕМ shift_cancellations на проде - там рабочие данные!
    # Таблица shift_cancellations уже существует на проде, не трогаем её
    # op.drop_index('ix_shift_cancellations_cancellation_reason', table_name='shift_cancellations')
    # op.drop_index('ix_shift_cancellations_cancelled_by_type', table_name='shift_cancellations')
    # op.drop_index('ix_shift_cancellations_created_at', table_name='shift_cancellations')
    # op.drop_index('ix_shift_cancellations_employee_id', table_name='shift_cancellations')
    # op.drop_index('ix_shift_cancellations_fine_applied', table_name='shift_cancellations')
    # op.drop_index('ix_shift_cancellations_payroll_adjustment_id', table_name='shift_cancellations')
    # op.drop_index('ix_shift_cancellations_shift_schedule_id', table_name='shift_cancellations')
    # op.drop_table('shift_cancellations')
    op.drop_index('ix_settings_history_created_at', table_name='settings_history')
    op.drop_index('ix_settings_history_id', table_name='settings_history')
    op.drop_index('ix_settings_history_setting_key', table_name='settings_history')
    op.drop_table('settings_history')
    op.alter_column('contracts', 'hourly_rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Почасовая ставка в рублях',
               existing_nullable=True)
    op.alter_column('contracts', 'use_contract_rate',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Использовать ставку из договора (приоритет над объектом/тайм-слотом)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('contracts', 'payment_system_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Система оплаты труда (по умолчанию simple_hourly)',
               existing_nullable=True)
    op.alter_column('contracts', 'use_contract_payment_system',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Приоритет системы оплаты из договора (аналог use_contract_rate)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('contracts', 'payment_schedule_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='График выплат для сотрудника',
               existing_nullable=True)
    op.drop_index('idx_contracts_payment_schedule_id', table_name='contracts')
    op.drop_index('idx_contracts_payment_system_id', table_name='contracts')
    op.drop_index('idx_contracts_use_contract_payment_system', table_name='contracts')
    op.drop_index('idx_contracts_use_contract_rate', table_name='contracts')
    op.create_index(op.f('ix_contracts_payment_schedule_id'), 'contracts', ['payment_schedule_id'], unique=False)
    op.create_index(op.f('ix_contracts_payment_system_id'), 'contracts', ['payment_system_id'], unique=False)
    op.create_index(op.f('ix_contracts_use_contract_payment_system'), 'contracts', ['use_contract_payment_system'], unique=False)
    op.create_index(op.f('ix_contracts_use_contract_rate'), 'contracts', ['use_contract_rate'], unique=False)
    op.alter_column('employee_payments', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Способ: cash, bank_transfer, card, other',
               existing_nullable=False)
    op.alter_column('employee_payments', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Статус: pending, completed, failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index('idx_employee_payments_employee_id', table_name='employee_payments')
    op.drop_index('idx_employee_payments_id', table_name='employee_payments')
    op.drop_index('idx_employee_payments_payment_date', table_name='employee_payments')
    op.drop_index('idx_employee_payments_payment_details', table_name='employee_payments', postgresql_using='gin')
    op.drop_index('idx_employee_payments_payroll_entry_id', table_name='employee_payments')
    op.drop_index('idx_employee_payments_status', table_name='employee_payments')
    op.create_index(op.f('ix_employee_payments_employee_id'), 'employee_payments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_payments_id'), 'employee_payments', ['id'], unique=False)
    op.create_index(op.f('ix_employee_payments_payment_date'), 'employee_payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_employee_payments_payroll_entry_id'), 'employee_payments', ['payroll_entry_id'], unique=False)
    op.create_index(op.f('ix_employee_payments_status'), 'employee_payments', ['status'], unique=False)
    op.drop_table_comment(
        'employee_payments',
        existing_comment='Факты выплат сотрудникам',
        schema=None
    )
    op.drop_index('ix_notifications_user_status', table_name='notifications')
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.alter_column('objects', 'shift_tasks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Задачи на смену в формате JSON: [{"text": "Уборка", "is_mandatory": true, "deduction_amount": 100.0}]',
               existing_nullable=True)
    op.alter_column('objects', 'payment_system_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Система оплаты для объекта (переопределяет org_unit)',
               existing_nullable=True)
    op.alter_column('objects', 'payment_schedule_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='График выплат для объекта (переопределяет org_unit)',
               existing_nullable=True)
    op.alter_column('objects', 'inherit_late_settings',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Наследовать настройки штрафов от подразделения',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('objects', 'late_threshold_minutes',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Допустимое время опозданий в минутах (может быть отрицательным)',
               existing_nullable=True)
    op.alter_column('objects', 'late_penalty_per_minute',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Стоимость минуты штрафа за опоздание в рублях',
               existing_nullable=True)
    op.alter_column('objects', 'org_unit_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Подразделение, к которому относится объект',
               existing_nullable=True)
    op.drop_index('idx_objects_inherit_late_settings', table_name='objects')
    op.drop_index('idx_objects_org_unit_id', table_name='objects')
    op.drop_index('idx_objects_payment_schedule_id', table_name='objects')
    op.drop_index('idx_objects_payment_system_id', table_name='objects')
    op.drop_index('ix_objects_telegram_report_chat_id', table_name='objects')
    op.create_index(op.f('ix_objects_inherit_late_settings'), 'objects', ['inherit_late_settings'], unique=False)
    op.create_index(op.f('ix_objects_org_unit_id'), 'objects', ['org_unit_id'], unique=False)
    op.create_index(op.f('ix_objects_payment_schedule_id'), 'objects', ['payment_schedule_id'], unique=False)
    op.create_index(op.f('ix_objects_payment_system_id'), 'objects', ['payment_system_id'], unique=False)
    op.alter_column('org_structure_units', 'parent_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Родительское подразделение (для древовидной структуры)',
               existing_nullable=True)
    op.alter_column('org_structure_units', 'inherit_late_settings',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Наследовать настройки штрафов от родителя',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('org_structure_units', 'late_threshold_minutes',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Допустимое опоздание в минутах',
               existing_nullable=True)
    op.alter_column('org_structure_units', 'late_penalty_per_minute',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Стоимость минуты штрафа в рублях',
               existing_nullable=True)
    op.alter_column('org_structure_units', 'level',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Уровень в иерархии (0 - корень)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_org_units_is_active', table_name='org_structure_units')
    op.drop_index('idx_org_units_level', table_name='org_structure_units')
    op.drop_index('idx_org_units_owner_id', table_name='org_structure_units')
    op.drop_index('idx_org_units_parent_id', table_name='org_structure_units')
    op.drop_index('ix_org_structure_units_telegram_report_chat_id', table_name='org_structure_units')
    op.create_index(op.f('ix_org_structure_units_id'), 'org_structure_units', ['id'], unique=False)
    op.create_index(op.f('ix_org_structure_units_level'), 'org_structure_units', ['level'], unique=False)
    op.create_index(op.f('ix_org_structure_units_owner_id'), 'org_structure_units', ['owner_id'], unique=False)
    op.create_index(op.f('ix_org_structure_units_parent_id'), 'org_structure_units', ['parent_id'], unique=False)
    op.drop_table_comment(
        'org_structure_units',
        existing_comment='Организационная структура (подразделения)',
        schema=None
    )
    op.alter_column('payment_schedules', 'frequency',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Частота выплат (daily, weekly, monthly)',
               existing_nullable=False)
    op.alter_column('payment_schedules', 'payment_period',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Период расчета в формате JSON: {type, description, calc_rules}',
               existing_nullable=False)
    op.alter_column('payment_schedules', 'payment_day',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='День выплаты: для weekly (1-7), для monthly (1-31)',
               existing_nullable=False)
    op.alter_column('payment_schedules', 'owner_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Владелец кастомного графика (NULL для системных)',
               existing_nullable=True)
    op.alter_column('payment_schedules', 'object_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Привязка к конкретному объекту (NULL для общих)',
               existing_nullable=True)
    op.alter_column('payment_schedules', 'is_custom',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Кастомный график (созданный пользователем)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_payment_schedules_frequency', table_name='payment_schedules')
    op.drop_index('idx_payment_schedules_id', table_name='payment_schedules')
    op.drop_index('idx_payment_schedules_is_active', table_name='payment_schedules')
    op.drop_index('idx_payment_schedules_is_custom', table_name='payment_schedules')
    op.drop_index('idx_payment_schedules_object_id', table_name='payment_schedules')
    op.drop_index('idx_payment_schedules_owner_id', table_name='payment_schedules')
    op.drop_index('idx_payment_schedules_payment_period', table_name='payment_schedules', postgresql_using='gin')
    op.create_index(op.f('ix_payment_schedules_frequency'), 'payment_schedules', ['frequency'], unique=False)
    op.create_index(op.f('ix_payment_schedules_id'), 'payment_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_payment_schedules_is_active'), 'payment_schedules', ['is_active'], unique=False)
    op.create_index(op.f('ix_payment_schedules_is_custom'), 'payment_schedules', ['is_custom'], unique=False)
    op.create_index(op.f('ix_payment_schedules_object_id'), 'payment_schedules', ['object_id'], unique=False)
    op.create_index(op.f('ix_payment_schedules_owner_id'), 'payment_schedules', ['owner_id'], unique=False)
    op.drop_table_comment(
        'payment_schedules',
        existing_comment='Графики выплат',
        schema=None
    )
    op.alter_column('payment_systems', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Уникальный код системы (simple_hourly, salary, hourly_bonus)',
               existing_nullable=False)
    op.alter_column('payment_systems', 'calculation_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Тип расчета (hourly, salary, hourly_bonus)',
               existing_nullable=False)
    op.drop_index('idx_payment_systems_code', table_name='payment_systems')
    op.drop_index('idx_payment_systems_display_order', table_name='payment_systems')
    op.drop_index('idx_payment_systems_id', table_name='payment_systems')
    op.drop_index('idx_payment_systems_is_active', table_name='payment_systems')
    op.create_index(op.f('ix_payment_systems_code'), 'payment_systems', ['code'], unique=True)
    op.create_index(op.f('ix_payment_systems_display_order'), 'payment_systems', ['display_order'], unique=False)
    op.create_index(op.f('ix_payment_systems_id'), 'payment_systems', ['id'], unique=False)
    op.create_index(op.f('ix_payment_systems_is_active'), 'payment_systems', ['is_active'], unique=False)
    op.drop_table_comment(
        'payment_systems',
        existing_comment='Справочник видов систем оплаты труда',
        schema=None
    )
    op.alter_column('payroll_adjustments', 'adjustment_type',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Тип корректировки: shift_base, late_start, task_bonus, task_penalty, manual_bonus, manual_deduction',
               existing_nullable=False)
    op.alter_column('payroll_adjustments', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Сумма корректировки (может быть + или -)',
               existing_nullable=False)
    op.alter_column('payroll_adjustments', 'is_applied',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Применено к payroll_entry',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('payroll_adjustments', 'edit_history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='История изменений [{timestamp, user_id, field, old_value, new_value}]',
               existing_nullable=True)
    op.drop_index('idx_payroll_adjustments_adjustment_type', table_name='payroll_adjustments')
    op.drop_index('idx_payroll_adjustments_created_at', table_name='payroll_adjustments')
    op.drop_index('idx_payroll_adjustments_created_by', table_name='payroll_adjustments')
    op.drop_index('idx_payroll_adjustments_employee_id', table_name='payroll_adjustments')
    op.drop_index('idx_payroll_adjustments_is_applied', table_name='payroll_adjustments')
    op.drop_index('idx_payroll_adjustments_object_id', table_name='payroll_adjustments')
    op.drop_index('idx_payroll_adjustments_payroll_entry_id', table_name='payroll_adjustments')
    op.drop_index('idx_payroll_adjustments_shift_id', table_name='payroll_adjustments')
    op.drop_index('idx_payroll_adjustments_updated_by', table_name='payroll_adjustments')
    op.create_index(op.f('ix_payroll_adjustments_adjustment_type'), 'payroll_adjustments', ['adjustment_type'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_created_at'), 'payroll_adjustments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_created_by'), 'payroll_adjustments', ['created_by'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_employee_id'), 'payroll_adjustments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_id'), 'payroll_adjustments', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_is_applied'), 'payroll_adjustments', ['is_applied'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_object_id'), 'payroll_adjustments', ['object_id'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_payroll_entry_id'), 'payroll_adjustments', ['payroll_entry_id'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_shift_id'), 'payroll_adjustments', ['shift_id'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_updated_by'), 'payroll_adjustments', ['updated_by'], unique=False)
    op.drop_table_comment(
        'payroll_adjustments',
        existing_comment='Единая таблица корректировок начислений (смены, штрафы, премии, задачи)',
        schema=None
    )
    op.alter_column('payroll_entries', 'calculation_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Детали расчета в JSON (смены, корректировки)',
               existing_nullable=True)
    op.drop_index('idx_payroll_entries_calculation_details', table_name='payroll_entries', postgresql_using='gin')
    op.drop_index('idx_payroll_entries_contract_id', table_name='payroll_entries')
    op.drop_index('idx_payroll_entries_employee_id', table_name='payroll_entries')
    op.drop_index('idx_payroll_entries_id', table_name='payroll_entries')
    op.drop_index('idx_payroll_entries_object_id', table_name='payroll_entries')
    op.drop_index('idx_payroll_entries_period_end', table_name='payroll_entries')
    op.drop_index('idx_payroll_entries_period_start', table_name='payroll_entries')
    op.create_index(op.f('ix_payroll_entries_contract_id'), 'payroll_entries', ['contract_id'], unique=False)
    op.create_index(op.f('ix_payroll_entries_employee_id'), 'payroll_entries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_entries_id'), 'payroll_entries', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_entries_object_id'), 'payroll_entries', ['object_id'], unique=False)
    op.create_index(op.f('ix_payroll_entries_period_end'), 'payroll_entries', ['period_end'], unique=False)
    op.create_index(op.f('ix_payroll_entries_period_start'), 'payroll_entries', ['period_start'], unique=False)
    op.drop_table_comment(
        'payroll_entries',
        existing_comment='Записи начислений зарплаты',
        schema=None
    )
    op.drop_index('ix_shifts_actual_start', table_name='shifts')
    op.drop_index('ix_shifts_planned_start', table_name='shifts')
    op.alter_column('timeslot_task_templates', 'is_mandatory',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Обязательная ли задача',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('timeslot_task_templates', 'deduction_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Сумма удержания за невыполнение (в рублях)',
               existing_nullable=True)
    op.alter_column('timeslot_task_templates', 'display_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Порядок отображения задач',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_timeslot_task_templates_id', table_name='timeslot_task_templates')
    op.drop_index('idx_timeslot_task_templates_timeslot_id', table_name='timeslot_task_templates')
    op.create_index(op.f('ix_timeslot_task_templates_id'), 'timeslot_task_templates', ['id'], unique=False)
    op.create_index(op.f('ix_timeslot_task_templates_timeslot_id'), 'timeslot_task_templates', ['timeslot_id'], unique=False)
    op.drop_table_comment(
        'timeslot_task_templates',
        existing_comment='Шаблоны задач для тайм-слотов',
        schema=None
    )
    op.alter_column('users', 'is_test_user',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_test_user',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.create_table_comment(
        'timeslot_task_templates',
        'Шаблоны задач для тайм-слотов',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_timeslot_task_templates_timeslot_id'), table_name='timeslot_task_templates')
    op.drop_index(op.f('ix_timeslot_task_templates_id'), table_name='timeslot_task_templates')
    op.create_index('idx_timeslot_task_templates_timeslot_id', 'timeslot_task_templates', ['timeslot_id'], unique=False)
    op.create_index('idx_timeslot_task_templates_id', 'timeslot_task_templates', ['id'], unique=False)
    op.alter_column('timeslot_task_templates', 'display_order',
               existing_type=sa.INTEGER(),
               comment='Порядок отображения задач',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('timeslot_task_templates', 'deduction_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Сумма удержания за невыполнение (в рублях)',
               existing_nullable=True)
    op.alter_column('timeslot_task_templates', 'is_mandatory',
               existing_type=sa.BOOLEAN(),
               comment='Обязательная ли задача',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.create_index('ix_shifts_planned_start', 'shifts', ['planned_start'], unique=False)
    op.create_index('ix_shifts_actual_start', 'shifts', ['actual_start'], unique=False)
    op.create_table_comment(
        'payroll_entries',
        'Записи начислений зарплаты',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_payroll_entries_period_start'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_period_end'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_object_id'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_id'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_employee_id'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_contract_id'), table_name='payroll_entries')
    op.create_index('idx_payroll_entries_period_start', 'payroll_entries', ['period_start'], unique=False)
    op.create_index('idx_payroll_entries_period_end', 'payroll_entries', ['period_end'], unique=False)
    op.create_index('idx_payroll_entries_object_id', 'payroll_entries', ['object_id'], unique=False)
    op.create_index('idx_payroll_entries_id', 'payroll_entries', ['id'], unique=False)
    op.create_index('idx_payroll_entries_employee_id', 'payroll_entries', ['employee_id'], unique=False)
    op.create_index('idx_payroll_entries_contract_id', 'payroll_entries', ['contract_id'], unique=False)
    op.create_index('idx_payroll_entries_calculation_details', 'payroll_entries', ['calculation_details'], unique=False, postgresql_using='gin')
    op.alter_column('payroll_entries', 'calculation_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Детали расчета в JSON (смены, корректировки)',
               existing_nullable=True)
    op.create_table_comment(
        'payroll_adjustments',
        'Единая таблица корректировок начислений (смены, штрафы, премии, задачи)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_payroll_adjustments_updated_by'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_shift_id'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_payroll_entry_id'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_object_id'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_is_applied'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_id'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_employee_id'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_created_by'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_created_at'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_adjustment_type'), table_name='payroll_adjustments')
    op.create_index('idx_payroll_adjustments_updated_by', 'payroll_adjustments', ['updated_by'], unique=False)
    op.create_index('idx_payroll_adjustments_shift_id', 'payroll_adjustments', ['shift_id'], unique=False)
    op.create_index('idx_payroll_adjustments_payroll_entry_id', 'payroll_adjustments', ['payroll_entry_id'], unique=False)
    op.create_index('idx_payroll_adjustments_object_id', 'payroll_adjustments', ['object_id'], unique=False)
    op.create_index('idx_payroll_adjustments_is_applied', 'payroll_adjustments', ['is_applied'], unique=False)
    op.create_index('idx_payroll_adjustments_employee_id', 'payroll_adjustments', ['employee_id'], unique=False)
    op.create_index('idx_payroll_adjustments_created_by', 'payroll_adjustments', ['created_by'], unique=False)
    op.create_index('idx_payroll_adjustments_created_at', 'payroll_adjustments', ['created_at'], unique=False)
    op.create_index('idx_payroll_adjustments_adjustment_type', 'payroll_adjustments', ['adjustment_type'], unique=False)
    op.alter_column('payroll_adjustments', 'edit_history',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='История изменений [{timestamp, user_id, field, old_value, new_value}]',
               existing_nullable=True)
    op.alter_column('payroll_adjustments', 'is_applied',
               existing_type=sa.BOOLEAN(),
               comment='Применено к payroll_entry',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('payroll_adjustments', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Сумма корректировки (может быть + или -)',
               existing_nullable=False)
    op.alter_column('payroll_adjustments', 'adjustment_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Тип корректировки: shift_base, late_start, task_bonus, task_penalty, manual_bonus, manual_deduction',
               existing_nullable=False)
    op.create_table_comment(
        'payment_systems',
        'Справочник видов систем оплаты труда',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_payment_systems_is_active'), table_name='payment_systems')
    op.drop_index(op.f('ix_payment_systems_id'), table_name='payment_systems')
    op.drop_index(op.f('ix_payment_systems_display_order'), table_name='payment_systems')
    op.drop_index(op.f('ix_payment_systems_code'), table_name='payment_systems')
    op.create_index('idx_payment_systems_is_active', 'payment_systems', ['is_active'], unique=False)
    op.create_index('idx_payment_systems_id', 'payment_systems', ['id'], unique=False)
    op.create_index('idx_payment_systems_display_order', 'payment_systems', ['display_order'], unique=False)
    op.create_index('idx_payment_systems_code', 'payment_systems', ['code'], unique=False)
    op.alter_column('payment_systems', 'calculation_type',
               existing_type=sa.VARCHAR(length=50),
               comment='Тип расчета (hourly, salary, hourly_bonus)',
               existing_nullable=False)
    op.alter_column('payment_systems', 'code',
               existing_type=sa.VARCHAR(length=50),
               comment='Уникальный код системы (simple_hourly, salary, hourly_bonus)',
               existing_nullable=False)
    op.create_table_comment(
        'payment_schedules',
        'Графики выплат',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_payment_schedules_owner_id'), table_name='payment_schedules')
    op.drop_index(op.f('ix_payment_schedules_object_id'), table_name='payment_schedules')
    op.drop_index(op.f('ix_payment_schedules_is_custom'), table_name='payment_schedules')
    op.drop_index(op.f('ix_payment_schedules_is_active'), table_name='payment_schedules')
    op.drop_index(op.f('ix_payment_schedules_id'), table_name='payment_schedules')
    op.drop_index(op.f('ix_payment_schedules_frequency'), table_name='payment_schedules')
    op.create_index('idx_payment_schedules_payment_period', 'payment_schedules', ['payment_period'], unique=False, postgresql_using='gin')
    op.create_index('idx_payment_schedules_owner_id', 'payment_schedules', ['owner_id'], unique=False)
    op.create_index('idx_payment_schedules_object_id', 'payment_schedules', ['object_id'], unique=False)
    op.create_index('idx_payment_schedules_is_custom', 'payment_schedules', ['is_custom'], unique=False)
    op.create_index('idx_payment_schedules_is_active', 'payment_schedules', ['is_active'], unique=False)
    op.create_index('idx_payment_schedules_id', 'payment_schedules', ['id'], unique=False)
    op.create_index('idx_payment_schedules_frequency', 'payment_schedules', ['frequency'], unique=False)
    op.alter_column('payment_schedules', 'is_custom',
               existing_type=sa.BOOLEAN(),
               comment='Кастомный график (созданный пользователем)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('payment_schedules', 'object_id',
               existing_type=sa.INTEGER(),
               comment='Привязка к конкретному объекту (NULL для общих)',
               existing_nullable=True)
    op.alter_column('payment_schedules', 'owner_id',
               existing_type=sa.INTEGER(),
               comment='Владелец кастомного графика (NULL для системных)',
               existing_nullable=True)
    op.alter_column('payment_schedules', 'payment_day',
               existing_type=sa.INTEGER(),
               comment='День выплаты: для weekly (1-7), для monthly (1-31)',
               existing_nullable=False)
    op.alter_column('payment_schedules', 'payment_period',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Период расчета в формате JSON: {type, description, calc_rules}',
               existing_nullable=False)
    op.alter_column('payment_schedules', 'frequency',
               existing_type=sa.VARCHAR(length=50),
               comment='Частота выплат (daily, weekly, monthly)',
               existing_nullable=False)
    op.create_table_comment(
        'org_structure_units',
        'Организационная структура (подразделения)',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_org_structure_units_parent_id'), table_name='org_structure_units')
    op.drop_index(op.f('ix_org_structure_units_owner_id'), table_name='org_structure_units')
    op.drop_index(op.f('ix_org_structure_units_level'), table_name='org_structure_units')
    op.drop_index(op.f('ix_org_structure_units_id'), table_name='org_structure_units')
    op.create_index('ix_org_structure_units_telegram_report_chat_id', 'org_structure_units', ['telegram_report_chat_id'], unique=False)
    op.create_index('idx_org_units_parent_id', 'org_structure_units', ['parent_id'], unique=False)
    op.create_index('idx_org_units_owner_id', 'org_structure_units', ['owner_id'], unique=False)
    op.create_index('idx_org_units_level', 'org_structure_units', ['level'], unique=False)
    op.create_index('idx_org_units_is_active', 'org_structure_units', ['is_active'], unique=False)
    op.alter_column('org_structure_units', 'level',
               existing_type=sa.INTEGER(),
               comment='Уровень в иерархии (0 - корень)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('org_structure_units', 'late_penalty_per_minute',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Стоимость минуты штрафа в рублях',
               existing_nullable=True)
    op.alter_column('org_structure_units', 'late_threshold_minutes',
               existing_type=sa.INTEGER(),
               comment='Допустимое опоздание в минутах',
               existing_nullable=True)
    op.alter_column('org_structure_units', 'inherit_late_settings',
               existing_type=sa.BOOLEAN(),
               comment='Наследовать настройки штрафов от родителя',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('org_structure_units', 'parent_id',
               existing_type=sa.INTEGER(),
               comment='Родительское подразделение (для древовидной структуры)',
               existing_nullable=True)
    op.drop_index(op.f('ix_objects_payment_system_id'), table_name='objects')
    op.drop_index(op.f('ix_objects_payment_schedule_id'), table_name='objects')
    op.drop_index(op.f('ix_objects_org_unit_id'), table_name='objects')
    op.drop_index(op.f('ix_objects_inherit_late_settings'), table_name='objects')
    op.create_index('ix_objects_telegram_report_chat_id', 'objects', ['telegram_report_chat_id'], unique=False)
    op.create_index('idx_objects_payment_system_id', 'objects', ['payment_system_id'], unique=False)
    op.create_index('idx_objects_payment_schedule_id', 'objects', ['payment_schedule_id'], unique=False)
    op.create_index('idx_objects_org_unit_id', 'objects', ['org_unit_id'], unique=False)
    op.create_index('idx_objects_inherit_late_settings', 'objects', ['inherit_late_settings'], unique=False)
    op.alter_column('objects', 'org_unit_id',
               existing_type=sa.INTEGER(),
               comment='Подразделение, к которому относится объект',
               existing_nullable=True)
    op.alter_column('objects', 'late_penalty_per_minute',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Стоимость минуты штрафа за опоздание в рублях',
               existing_nullable=True)
    op.alter_column('objects', 'late_threshold_minutes',
               existing_type=sa.INTEGER(),
               comment='Допустимое время опозданий в минутах (может быть отрицательным)',
               existing_nullable=True)
    op.alter_column('objects', 'inherit_late_settings',
               existing_type=sa.BOOLEAN(),
               comment='Наследовать настройки штрафов от подразделения',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('objects', 'payment_schedule_id',
               existing_type=sa.INTEGER(),
               comment='График выплат для объекта (переопределяет org_unit)',
               existing_nullable=True)
    op.alter_column('objects', 'payment_system_id',
               existing_type=sa.INTEGER(),
               comment='Система оплаты для объекта (переопределяет org_unit)',
               existing_nullable=True)
    op.alter_column('objects', 'shift_tasks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Задачи на смену в формате JSON: [{"text": "Уборка", "is_mandatory": true, "deduction_amount": 100.0}]',
               existing_nullable=True)
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.create_index('ix_notifications_user_status', 'notifications', ['user_id', 'status'], unique=False)
    op.create_table_comment(
        'employee_payments',
        'Факты выплат сотрудникам',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_employee_payments_status'), table_name='employee_payments')
    op.drop_index(op.f('ix_employee_payments_payroll_entry_id'), table_name='employee_payments')
    op.drop_index(op.f('ix_employee_payments_payment_date'), table_name='employee_payments')
    op.drop_index(op.f('ix_employee_payments_id'), table_name='employee_payments')
    op.drop_index(op.f('ix_employee_payments_employee_id'), table_name='employee_payments')
    op.create_index('idx_employee_payments_status', 'employee_payments', ['status'], unique=False)
    op.create_index('idx_employee_payments_payroll_entry_id', 'employee_payments', ['payroll_entry_id'], unique=False)
    op.create_index('idx_employee_payments_payment_details', 'employee_payments', ['payment_details'], unique=False, postgresql_using='gin')
    op.create_index('idx_employee_payments_payment_date', 'employee_payments', ['payment_date'], unique=False)
    op.create_index('idx_employee_payments_id', 'employee_payments', ['id'], unique=False)
    op.create_index('idx_employee_payments_employee_id', 'employee_payments', ['employee_id'], unique=False)
    op.alter_column('employee_payments', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='Статус: pending, completed, failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('employee_payments', 'payment_method',
               existing_type=sa.VARCHAR(length=50),
               comment='Способ: cash, bank_transfer, card, other',
               existing_nullable=False)
    op.drop_index(op.f('ix_contracts_use_contract_rate'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_use_contract_payment_system'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_payment_system_id'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_payment_schedule_id'), table_name='contracts')
    op.create_index('idx_contracts_use_contract_rate', 'contracts', ['use_contract_rate'], unique=False)
    op.create_index('idx_contracts_use_contract_payment_system', 'contracts', ['use_contract_payment_system'], unique=False)
    op.create_index('idx_contracts_payment_system_id', 'contracts', ['payment_system_id'], unique=False)
    op.create_index('idx_contracts_payment_schedule_id', 'contracts', ['payment_schedule_id'], unique=False)
    op.alter_column('contracts', 'payment_schedule_id',
               existing_type=sa.INTEGER(),
               comment='График выплат для сотрудника',
               existing_nullable=True)
    op.alter_column('contracts', 'use_contract_payment_system',
               existing_type=sa.BOOLEAN(),
               comment='Приоритет системы оплаты из договора (аналог use_contract_rate)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('contracts', 'payment_system_id',
               existing_type=sa.INTEGER(),
               comment='Система оплаты труда (по умолчанию simple_hourly)',
               existing_nullable=True)
    op.alter_column('contracts', 'use_contract_rate',
               existing_type=sa.BOOLEAN(),
               comment='Использовать ставку из договора (приоритет над объектом/тайм-слотом)',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('contracts', 'hourly_rate',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Почасовая ставка в рублях',
               existing_nullable=True)
    op.create_table('settings_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('setting_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('old_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('new_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('changed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('change_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='settings_history_pkey')
    )
    op.create_index('ix_settings_history_setting_key', 'settings_history', ['setting_key'], unique=False)
    op.create_index('ix_settings_history_id', 'settings_history', ['id'], unique=False)
    op.create_index('ix_settings_history_created_at', 'settings_history', ['created_at'], unique=False)
    # КРИТИЧНО: НЕ ПЕРЕСОЗДАЁМ shift_cancellations - таблица уже существует на проде!
    # Если нужно изменить структуру - используйте ALTER TABLE, не DROP/CREATE
    pass  # Заглушка, чтобы миграция не сломалась
    """
    op.create_table('shift_cancellations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shift_schedule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cancelled_by_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cancelled_by_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('cancellation_reason', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('reason_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hours_before_shift', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('document_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('document_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('verified_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('fine_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('fine_reason', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fine_applied', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('payroll_adjustment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('contract_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], name='fk_shift_cancellations_cancelled_by'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], name='fk_shift_cancellations_contract'),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], name='fk_shift_cancellations_employee'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], name='fk_shift_cancellations_object'),
    sa.ForeignKeyConstraint(['payroll_adjustment_id'], ['payroll_adjustments.id'], name='fk_shift_cancellations_payroll_adj'),
    sa.ForeignKeyConstraint(['shift_schedule_id'], ['shift_schedules.id'], name='fk_shift_cancellations_shift_schedule', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], name='fk_shift_cancellations_verified_by'),
    sa.PrimaryKeyConstraint('id', name='shift_cancellations_pkey')
    )
    op.create_index('ix_shift_cancellations_shift_schedule_id', 'shift_cancellations', ['shift_schedule_id'], unique=False)
    op.create_index('ix_shift_cancellations_payroll_adjustment_id', 'shift_cancellations', ['payroll_adjustment_id'], unique=False)
    op.create_index('ix_shift_cancellations_fine_applied', 'shift_cancellations', ['fine_applied'], unique=False)
    op.create_index('ix_shift_cancellations_employee_id', 'shift_cancellations', ['employee_id'], unique=False)
    op.create_index('ix_shift_cancellations_created_at', 'shift_cancellations', ['created_at'], unique=False)
    op.create_index('ix_shift_cancellations_cancelled_by_type', 'shift_cancellations', ['cancelled_by_type'], unique=False)
    op.create_index('ix_shift_cancellations_cancellation_reason', 'shift_cancellations', ['cancellation_reason'], unique=False)
    """
    op.create_table('shift_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shift_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('task_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Источник задачи: object, timeslot, manual'),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='ID источника (объекта/тайм-слота)'),
    sa.Column('is_mandatory', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('requires_media', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('deduction_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Сумма штрафа/премии за невыполнение/выполнение'),
    sa.Column('is_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('media_refs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='JSON ссылки на медиа-отчеты'),
    sa.Column('correction_ref', sa.INTEGER(), autoincrement=False, nullable=True, comment='ID записи корректировки начисления (связь с payroll_adjustments)'),
    sa.Column('cost', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True, comment='Фактическая премия/штраф по задаче'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='shift_tasks_created_by_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name='shift_tasks_shift_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='shift_tasks_pkey'),
    comment='Журнал задач смен (конфигурация + статусы выполнения)'
    )
    op.create_index('idx_shift_tasks_source', 'shift_tasks', ['source'], unique=False)
    op.create_index('idx_shift_tasks_shift_id', 'shift_tasks', ['shift_id'], unique=False)
    op.create_index('idx_shift_tasks_is_mandatory', 'shift_tasks', ['is_mandatory'], unique=False)
    op.create_index('idx_shift_tasks_is_completed', 'shift_tasks', ['is_completed'], unique=False)
    op.create_index('idx_shift_tasks_id', 'shift_tasks', ['id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='system_settings_pkey'),
    sa.UniqueConstraint('key', name='system_settings_key_key')
    )
    op.create_index('ix_system_settings_key', 'system_settings', ['key'], unique=False)
    op.create_index('ix_system_settings_id', 'system_settings', ['id'], unique=False)
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_index(op.f('ix_organization_profiles_user_id'), table_name='organization_profiles')
    op.drop_index(op.f('ix_organization_profiles_id'), table_name='organization_profiles')
    op.drop_table('organization_profiles')
    op.drop_index(op.f('ix_system_features_key'), table_name='system_features')
    op.drop_index(op.f('ix_system_features_id'), table_name='system_features')
    op.drop_table('system_features')
    # ### end Alembic commands ###
