"""добавлено_поле_preferred_work_types

Revision ID: a9e895d0cfca
Revises: 8f5fd7e8c46c
Create Date: 2025-09-23 20:42:36.648538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9e895d0cfca'
down_revision: Union[str, Sequence[str], None] = '8f5fd7e8c46c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferred_work_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferred_work_types')
    # ### end Alembic commands ###
