"""add_shift_schedules_table

Revision ID: b348c85b3761
Revises: 97844e8c2d47
Create Date: 2025-08-22 00:43:07.674151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b348c85b3761'
down_revision: Union[str, Sequence[str], None] = '97844e8c2d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=True),
    sa.Column('actual_shift_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actual_shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_schedules_id'), 'shift_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_shift_schedules_object_id'), 'shift_schedules', ['object_id'], unique=False)
    op.create_index(op.f('ix_shift_schedules_planned_end'), 'shift_schedules', ['planned_end'], unique=False)
    op.create_index(op.f('ix_shift_schedules_planned_start'), 'shift_schedules', ['planned_start'], unique=False)
    op.create_index(op.f('ix_shift_schedules_status'), 'shift_schedules', ['status'], unique=False)
    op.create_index(op.f('ix_shift_schedules_user_id'), 'shift_schedules', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_schedules_user_id'), table_name='shift_schedules')
    op.drop_index(op.f('ix_shift_schedules_status'), table_name='shift_schedules')
    op.drop_index(op.f('ix_shift_schedules_planned_start'), table_name='shift_schedules')
    op.drop_index(op.f('ix_shift_schedules_planned_end'), table_name='shift_schedules')
    op.drop_index(op.f('ix_shift_schedules_object_id'), table_name='shift_schedules')
    op.drop_index(op.f('ix_shift_schedules_id'), table_name='shift_schedules')
    op.drop_table('shift_schedules')
    # ### end Alembic commands ###
