"""add_time_slot_id_to_shift_schedules

Revision ID: ba14240f3228
Revises: 7d2f3a2b54d1
Create Date: 2025-09-07 10:03:23.467862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba14240f3228'
down_revision: Union[str, Sequence[str], None] = '7d2f3a2b54d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_schedules', sa.Column('time_slot_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_shift_schedules_time_slot_id'), 'shift_schedules', ['time_slot_id'], unique=False)
    op.create_foreign_key(None, 'shift_schedules', 'time_slots', ['time_slot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shift_schedules', type_='foreignkey')
    op.drop_index(op.f('ix_shift_schedules_time_slot_id'), table_name='shift_schedules')
    op.drop_column('shift_schedules', 'time_slot_id')
    # ### end Alembic commands ###
