"""add_planning_templates_tables

Revision ID: cdf426d5d4ec
Revises: 4b2fa139dbe2
Create Date: 2025-09-07 07:16:18.324983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdf426d5d4ec'
down_revision: Union[str, Sequence[str], None] = '4b2fa139dbe2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planning_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название шаблона'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание шаблона'),
    sa.Column('owner_telegram_id', sa.Integer(), nullable=False, comment='Telegram ID владельца'),
    sa.Column('object_id', sa.Integer(), nullable=False, comment='ID объекта'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Активен ли шаблон'),
    sa.Column('is_public', sa.Boolean(), nullable=True, comment='Публичный ли шаблон (для всех владельцев)'),
    sa.Column('start_time', sa.String(length=5), nullable=False, comment='Время начала (HH:MM)'),
    sa.Column('end_time', sa.String(length=5), nullable=False, comment='Время окончания (HH:MM)'),
    sa.Column('hourly_rate', sa.Integer(), nullable=False, comment='Почасовая ставка'),
    sa.Column('repeat_type', sa.String(length=20), nullable=True, comment='Тип повторения: none, daily, weekly, monthly'),
    sa.Column('repeat_days', sa.String(length=20), nullable=True, comment='Дни недели для повторения (1,2,3,4,5,6,7)'),
    sa.Column('repeat_interval', sa.Integer(), nullable=True, comment='Интервал повторения'),
    sa.Column('repeat_end_date', sa.DateTime(), nullable=True, comment='Дата окончания повторения'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Дата обновления'),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_templates_id'), 'planning_templates', ['id'], unique=False)
    op.create_index(op.f('ix_planning_templates_owner_telegram_id'), 'planning_templates', ['owner_telegram_id'], unique=False)
    op.create_table('template_time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False, comment='ID шаблона'),
    sa.Column('day_of_week', sa.Integer(), nullable=False, comment='День недели (0=Понедельник, 6=Воскресенье)'),
    sa.Column('start_time', sa.String(length=5), nullable=False, comment='Время начала (HH:MM)'),
    sa.Column('end_time', sa.String(length=5), nullable=False, comment='Время окончания (HH:MM)'),
    sa.Column('hourly_rate', sa.Integer(), nullable=False, comment='Почасовая ставка'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Активен ли слот'),
    sa.ForeignKeyConstraint(['template_id'], ['planning_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_time_slots_id'), 'template_time_slots', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_time_slots_id'), table_name='template_time_slots')
    op.drop_table('template_time_slots')
    op.drop_index(op.f('ix_planning_templates_owner_telegram_id'), table_name='planning_templates')
    op.drop_index(op.f('ix_planning_templates_id'), table_name='planning_templates')
    op.drop_table('planning_templates')
    # ### end Alembic commands ###
