"""extend_owner_profile_and_org_structure

Revision ID: da5277f32d13
Revises: a266c36de460
Create Date: 2025-10-19 11:52:08.086510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da5277f32d13'
down_revision: Union[str, Sequence[str], None] = 'a266c36de460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Не удаляем spatial_ref_sys - системная таблица PostGIS
    # op.drop_table('spatial_ref_sys')
    op.add_column('org_structure_units', sa.Column('organization_profile_id', sa.Integer(), nullable=True, comment='Профиль организации для договоров в этом подразделении'))
    op.create_index(op.f('ix_org_structure_units_organization_profile_id'), 'org_structure_units', ['organization_profile_id'], unique=False)
    op.create_foreign_key(None, 'org_structure_units', 'organization_profiles', ['organization_profile_id'], ['id'], ondelete='SET NULL')
    op.add_column('owner_profiles', sa.Column('about_company', sa.Text(), nullable=True, comment='О компании - описание, история, масштаб'))
    op.add_column('owner_profiles', sa.Column('values', sa.Text(), nullable=True, comment='Ценности компании - принципы, структура'))
    op.add_column('owner_profiles', sa.Column('photos', sa.JSON(), nullable=False, comment='Фотографии компании (массив URL/путей, до 5 шт)'))
    op.add_column('owner_profiles', sa.Column('contact_phone', sa.String(length=20), nullable=True, comment='Телефон для связи'))
    op.add_column('owner_profiles', sa.Column('contact_messengers', sa.JSON(), nullable=False, comment='Активные мессенджеры: whatsapp, telegram, max'))
    op.add_column('owner_profiles', sa.Column('enabled_features', sa.JSON(), nullable=False, comment='Включенные дополнительные функции (массив ключей функций)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('owner_profiles', 'enabled_features')
    op.drop_column('owner_profiles', 'contact_messengers')
    op.drop_column('owner_profiles', 'contact_phone')
    op.drop_column('owner_profiles', 'photos')
    op.drop_column('owner_profiles', 'values')
    op.drop_column('owner_profiles', 'about_company')
    op.drop_constraint(None, 'org_structure_units', type_='foreignkey')
    op.drop_index(op.f('ix_org_structure_units_organization_profile_id'), table_name='org_structure_units')
    op.drop_column('org_structure_units', 'organization_profile_id')
    # Не создаём spatial_ref_sys - системная таблица PostGIS
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    # ### end Alembic commands ###
